### ISSUE TITLE
FragmentTabHost 下失效问题

### ISSUE THREAD

**Issue by tv009** [pengwei1024/JsBridge#10]
具体描述:
JS通过桥调用android HTTP方法得到返回后回调通知JS
在单一activity窗口 测试时没有问题的
现在多页面同时打开3个WEBVIEW  在HTTP得到返回调用JS这个环节则失败

我不是很理解,但觉得应该是多WEBVIEW 下 调用3份js 哪一份出现的问题,
望给出解决方案!

**Comment by pengwei1024** [comment]
你的意思是三个 fragment 里面有三个 webview, 调用 js 的方法不能回调是吗？

**Comment by tv009** [comment]
对对

**Comment by pengwei1024** [comment]
能支持啊，如果 context 一样，一个 JsBridge 就行。我在分支写了一个 TabActivity 的例子，你参考试试？https://github.com/pengwei1024/JsBridge/blob/Laboratory/sample/src/main/java/com/apkfuns/jsbridgesample/view/TabActivity.java

**Comment by tv009** [comment]
我先试试列子去

**Comment by tv009** [comment]
![image](https://user-images.githubusercontent.com/3796662/30726985-d9296408-9f80-11e7-9f18-e394b2865b79.png)
这里是我通过网页调用Android发送HTTP时 远程调试发现的,每次点击都将增加回调,并且越来越多,这是否是问题呢 ?

**Comment by pengwei1024** [comment]
这应该是JS 端的问题吧，回调这么多而且 id 还不一样，说明 js 请求了这么多次，你找找看 js 是不是在频繁请求

**Comment by tv009** [comment]
问题解决了,由于需求比较特殊,现在在每个webview使用的地方 采用 jsBridge.clone(),由于这个类是单例,自己增加了克隆方法!
