### ISSUE TITLE
更新日志

### ISSUE THREAD

**Issue by brandlee** [pengwei1024/JsBridge#11]
麻烦请教一下，第一次引入这个库的时候，版本还是2.0.1，现在我看已经是2.2.1了，麻烦请教一下有什么更新么？

还有一个问题就是，如果在activity的onDestroy中没有调用jsBridge.release()的话，此时我重新打开一个新的界面，会导致JsBridge的调用还会响应的问题吧

**Comment by pengwei1024** [comment]
更新内容基本上都是优化注入字符串内容，加快注入速度。建议最好执行下release，release做了内存的回收，不会影响新页面加载。因为JsBridge对象绑定了context，存在单例可能会导致Activity不能被释放内存泄露

**Comment by brandlee** [comment]
这是一个问题，还有一个问题请教一下，如果webview作为recyclerview的一个item，release的执行时机具体应该在哪块呢？

**Comment by pengwei1024** [comment]
就像上面说的，release其实就是做了一些垃圾回收，所以建议在Activity 或者 Fragment 的 onDestroy里执行，并不涉及到View，所以Recyclerview的复用是没关系的
