### ISSUE TITLE
在魅族手机上有时候不管用,不知道跟框架有关吗

### ISSUE THREAD

**Issue by tv009** [pengwei1024/JsBridge#12]
05-11 19:36:30.644 10839-10839/com.android.like E/chromium: [ERROR:aw_autofill_client.cc(175)] Not implemented reached in virtual void android_webview::AwAutofillClient::OnFirstUserGestureObserved()
05-11 19:36:31.024 10839-10839/com.android.like E/chromium: [ERROR:aw_autofill_client.cc(175)] Not implemented reached in virtual void android_webview::AwAutofillClient::OnFirstUserGestureObserved()
05-11 19:36:31.261 10839-10839/com.android.like E/chromium: [ERROR:aw_autofill_client.cc(175)] Not implemented reached in virtual void android_webview::AwAutofillClient::OnFirstUserGestureObserved()
05-11 19:36:31.435 10839-10839/com.android.like E/chromium: [ERROR:aw_autofill_client.cc(175)] Not implemented reached in virtual void android_webview::AwAutofillClient::OnFirstUserGestureObserved()
05-11 19:36:31.623 10839-10839/com.android.like E/chromium: [ERROR:aw_autofill_client.cc(175)] Not implemented reached in virtual void android_webview::AwAutofillClient::OnFirstUserGestureObserved()
05-11 19:36:31.795 10839-10839/com.android.like E/chromium: [ERROR:aw_autofill_client.cc(175)] Not implemented reached in virtual void android_webview::AwAutofillClient::OnFirstUserGestureObserved()
05-11 19:36:31.970 10839-10839/com.android.like E/chromium: [ERROR:aw_autofill_client.cc(175)] Not implemented reached in virtual void android_webview::AwAutofillClient::OnFirstUserGestureObserved()
05-11 19:36:32.196 10839-10839/com.android.like E/chromium: [ERROR:aw_autofill_client.cc(175)] Not implemented reached in virtual void android_webview::AwAutofillClient::OnFirstUserGestureObserved()
05-11 19:36:32.379 10839-10839/com.android.like E/chromium: [ERROR:aw_autofill_client.cc(175)] Not implemented reached in virtual void android_webview::AwAutofillClient::OnFirstUserGestureObserved()
05-11 19:36:32.564 10839-10839/com.android.like E/chromium: [ERROR:aw_autofill_client.cc(175)] Not implemented reached in virtual void android_webview::AwAutofillClient::OnFirstUserGestureObserved()
05-11 19:36:32.749 10839-10839/com.android.like E/chromium: [ERROR:aw_autofill_client.cc(175)] Not implemented reached in virtual void android_webview::AwAutofillClient::OnFirstUserGestureObserved()
05-11 19:36:32.955 10839-10839/com.android.like E/chromium: [ERROR:aw_autofill_client.cc(175)] Not implemented reached in virtual void android_webview::AwAutofillClient::OnFirstUserGestureObserved()
05-11 19:36:33.129 10839-10839/com.android.like E/chromium: [ERROR:aw_autofill_client.cc(175)] Not implemented reached in virtual void android_webview::AwAutofillClient::OnFirstUserGestureObserved()
05-11 19:36:33.334 10839-10839/com.android.like E/chromium: [ERROR:aw_autofill_client.cc(175)] Not implemented reached in virtual void android_webview::AwAutofillClient::OnFirstUserGestureObserved()

网页上点击一次  则实现JS调用JAVA一次,结果点一次 出一次这种提示,而且界面无反应,偶尔打开的时候可以点击,目前只在魅族上发现这个问题,我找到网络上有人有这个问题,但是他的实现方式和框架不同,所以不知道如何解决了
类同问题网址:https://blog.csdn.net/chen364567628/article/details/79309778

**Comment by pengwei1024** [comment]
你打开日志`JsBridgeConfig.debugMode(true)`，搜索`JsBridgeDebug` 看有没有错误日志。也可以看下网页是不是抛出错误了。用chrome://inspect/#devices  或者 vconsole都行。你这个错误像浏览器内核抛出的，是所有魅族手机都有这个问题吗？我提供的sample也有这个问题吗？

**Comment by tv009** [comment]
问题已经确认,确实是内核问题,点击无效是JS 原因,犯这个低级错误主要是chrome://inspect/#devices 这里在魅族手机上无法正常使用其调试说来也奇怪,魅族手机远程网页调试 各种视图全部错乱变形!还是特别感谢!

**Comment by zhangniuniu** [comment]
@tv009 请问最后怎么解决的

**Comment by liuhao722** [comment]
这边发现最终问题并非是H5的原因，而是客户端的JSBridgeWebView在initView时候loadUrl了两次，导致H5的方法失效！删除一次就可以了，但是在高版本手机上又没有这个问题，低版本上5.1的手机上才发现的这个问题；引以为戒...如果有类似的问题可以参照一下是否一样；

**Comment by jqorz** [comment]
> 问题已经确认,确实是内核问题,点击无效是JS 原因,犯这个低级错误主要是chrome://inspect/#devices 这里在魅族手机上无法正常使用其调试说来也奇怪,魅族手机远程网页调试 各种视图全部错乱变形!还是特别感谢!
低版本安卓5.1的手机，你得用chrome62调试才行。chrome63以后改了东西，不兼容低版本安卓webview调试
