### ISSUE TITLE
Release混淆编译问题

### ISSUE THREAD

**Issue by zcm-hu** [pengwei1024/JsBridge#15]

**Comment by pengwei1024** [comment]
@zcm-hu 这个和`JsBridge`没有关系吧，这应该是Android UI上的问题？

**Comment by zcm-hu** [comment]
@pengwei1024 尴尬，好像提issue  提错项目了...  不好意思。   大佬的JsBridge 很好用，已经集成在项目里面去了，顺便问一下，我开启了混淆  
-keep public class com.apkfuns.jsbridge.**{*;}
-keep class * extends com.apkfuns.jsbridge.module.JsModule
在Release包里面还是注入失败了，和混淆算法有关系吗  我只用了-optimizations !code/simplification/arithmetic,!field/*,!class/merging/* 这个

**Comment by pengwei1024** [comment]
目前的信息可能不太好定位。你可以根据TAG `JsBridgeDebug` 过滤下有没有什么错误信息。或者用`chrome://inspect/#devices` 看下有没有注入

**Comment by zcm-hu** [comment]
D/JsBridgeDebug: Protocol:JSBridge, LoadReadyMethod:onJSBridgeReady, moduleSize:1
D/JsBridgeDebug: onInjectJs finish

chrome://inspect/#devices    js报错了
VM17:1 TypeError: JSBridge.article.loadDetails is not a function
    at window.onJSBridgeReady (details.js:2)
    at JB_7b57993.OnJsBridgeReady (<anonymous>:1:818)
    at <anonymous>:1:1326

**Comment by zcm-hu** [comment]
我再检查检查看是不是其他混淆出问题了

**Comment by zcm-hu** [comment]
大佬，我下载你的这个demo 混淆后运行 也是找不到native注册的方法。能帮忙看看吗

**Comment by pengwei1024** [comment]
@zcm-hu 之前sample的`proguard-rules.pro`写的不完整，我补充了下测试混淆没有问题。你再试试？

**Comment by pengwei1024** [comment]
@zcm-hu sorry， 之前混淆写错了，因为集成JsModule的方法都是被反射调用的，所以混淆过程中全部去掉了。改成下面这样就行了

```
-keep public class com.apkfuns.jsbridge.**{*;}
-keep class * extends com.apkfuns.jsbridge.module.JsModule{*;}
```

**Comment by zcm-hu** [comment]
非常感谢，已经弄好了。
