### ISSUE TITLE
右下角那个vConsole怎么隐藏掉呀？

### ISSUE THREAD

**Issue by TangStudio** [pengwei1024/JsBridge#16]
如题，webview右下角那个vConsole怎么隐藏掉呀？

**Comment by pengwei1024** [comment]
去掉demo网页里面的`<script type="text/javascript" src="https://res.wx.qq.com/mmbizwap/zh_CN/htmledition/js/vconsole/2.5.1/vconsole.min.js"></script>` 就好，这是一个前端的库用于调试网页
