### ISSUE TITLE
前端的JsBridge这个类怎么调用呢？

### ISSUE THREAD

**Issue by TangStudio** [pengwei1024/JsBridge#18]
JsBridge.ajax({
    type:'GET',
    url:'xxx.com',
    dataType:'text'
    data:{a:1, b:'xx'},
    success:function(data){
    },
    error:function(err){
    }
})
JsBridge这个类，前端同学不知道从哪里调用

**Comment by TangStudio** [comment]
前端需要引用某个库还是JS里边本来就有的呢？前端同学表示很迷茫，谢谢

**Comment by tv009** [comment]
让他使用chrome中的远程调试手机页面 就可以调用了
