### ISSUE TITLE
如果加载js前注入，有办法吗？试过很多次没解决办法

### ISSUE THREAD

**Issue by mxjGG** [pengwei1024/JsBridge#19]

**Comment by mxjGG** [comment]
js想在一开始执行的就和原生进行交互，拿到自定义的module。试过很多次没解决办法

**Comment by pengwei1024** [comment]
我建议是在`window.onJsBridgeReady`里执行，如果真的需要在最开始可以尝试导出一份js文件，然后前端直接引用，而不是端上注入

**Comment by pengwei1024** [comment]
这种可以建议你用addJavascriptInterface，也是所有地方都可以调用的，只是不能分模块。导出一份JS给前端让前端引用也行，不过比较麻烦，你得改点源码输出一份js文件
