### ISSUE TITLE
JsBridge库精简

### ISSUE THREAD

**Issue by brandlee** [pengwei1024/JsBridge#20]
提个建议，感觉项目里面用到json解析的地方不多，这里不需要引进fastJson，一些对包大小敏感的app，fastjson感觉还是挺大的

**Comment by pengwei1024** [comment]
我很早前就去掉了fastjson依赖呀，你是不是版本还比较低？

**Comment by brandlee** [comment]
我现在的版本是2.0.1，升级到了2.1.1好了，应该是没有升级版本的原因哈
