### ISSUE TITLE
传递图片base64有问题

### ISSUE THREAD

**Issue by lodaDuan** [pengwei1024/JsBridge#21]
Refusing to load URL as it exceeds 2097152 characters，会报这个错，我是把图片转成base64字符，然后给h5。好像桥接有显示，字符串长度超过2M就不行了

**Comment by pengwei1024** [comment]
对呀，利用prompt传输的字符串是有限制的。如果非得传输这么大的字符串建议分多次传输。我觉得图片base64太大前端性能也是问题
