### ISSUE TITLE
请问JAVA层 如何直接调用JS的方法？

### ISSUE THREAD

**Issue by maobon** [pengwei1024/JsBridge#3]
感谢您的分享，发现demo中都是js层首先发起调用，调用Android 安卓执行完任务再回调JS。那么应用场景如果是Android首先发起调用 可以做到吗？如何操作 就是JS中直接监听Android的调用，这点可以做到吗？谢谢...

**Comment by pengwei1024** [comment]
android调用JS太简单了，所以就没有举例。用WebView.loadUrl("javascript:" + js语句) 记好了，我不太理解js监听安卓是啥意思？android可以调用js的方法，自然js就能知道android调用了

**Comment by maobon** [comment]
您的意思是根本就不需要用到框架了 那这样的话 是否会有安全问题呢？谢谢

**Comment by maobon** [comment]
感谢大神指点 现在看起来已经没有问题了

**Comment by kazeik** [comment]
WebView.loadUrl("javascript:" + js语句)  .这方法。6.0以上似乎不行了

**Comment by pengwei1024** [comment]
@kazeik 你是说targetSdkVersion 6.0 吗 ？还是6.0 的手机？ 应该都是可以正常使用的，看看是不是js语句错了？
