### ISSUE TITLE
作者你好，请问JSBridgeMethod的函数有办法让其在webview的js异步线程中调用吗

### ISSUE THREAD

**Issue by JavanZhu** [pengwei1024/JsBridge#30]
目前JSBridgeMethod注解的回调函数，最开始是从onJsPrompt开始执行的（onJsPrompt是运行在ui线程的），所以也运行在ui线程中，我理解的。

以前写的一些原生js接口都是JavascriptInterface注解写的，中间有一些同步代码，如果ui线程中执行会阻塞，所以请问下作者有没有办法让JSBridgeMethod注解的回调函数跟JavascriptInterface一样都运行在webview的js线程中。

**Comment by pengwei1024** [comment]
是的，prompt完全是在UI线程。用addJavascriptInteface 注册的方法是在js线程，因为不向下兼容，整体改动也比较大，没有时间就一直没改，推荐你自己可以把prompt改成 addJavascriptInteface来实现。也欢迎提交代码到这个仓库
