### ISSUE TITLE
CustomWebViewActivity里面都无法点击啊

### ISSUE THREAD

**Issue by colder112** [pengwei1024/JsBridge#6]
CustomWebViewActivity这个界面点击怎么都没反应啊。。

**Comment by colder112** [comment]
再次点击进systemWebview  报错   [ERROR:interface_registry.cc(104)] Failed to locate a binder for interface: autofill::mojom::PasswordManagerDriver

**Comment by pengwei1024** [comment]
这个错误不是 JsBridge 提示的哟，demo 最近我在调整，让效果更明显
