### ISSUE TITLE
关于onMyBridgeReady方法

### ISSUE THREAD

**Issue by brandlee** [pengwei1024/JsBridge#7]
麻烦请教一下，关于onMyBridgeReady是如何通知到前端JS已经注入完成的？这里还是有点模糊

**Comment by pengwei1024** [comment]
window.onMyBridgeReady 是一个全局的属性，当注入完成的时候，我判断下onMyBridgeReady 是不是存在  & 是一个方法，是的话就调用这个方法，方法里面的内容就执行了

**Comment by brandlee** [comment]
这个方法onMyBridgeReady中的MyBridge是设置的protocol吧，并不是直接写死的

**Comment by pengwei1024** [comment]
可以自己配置，没配置的时候有默认值。并不是protocol， 而是setLoadReadyMethod

**Comment by brandlee** [comment]
自己配制的地方在哪呢？而且我抓出来注入的js，确实是on+protocol+Ready拼接起来的

**Comment by pengwei1024** [comment]
```
JsBridgeConfig.getSetting().setProtocol("xxxxxx")
                .setLoadReadyMethod("zzzzzzz");
```

**Comment by dalong982242260** [comment]
这个方法必须写吗

**Comment by pengwei1024** [comment]
不写就是走默认的 on+protocol+Ready 呀
