### ISSUE TITLE
nexus5 6.0 js调用方法失败

### ISSUE THREAD

**Issue by hjw541988478** [pengwei1024/JsBridge#8]
Error SyntaxError: Unexpected end of input 这个错误，感觉和混淆有关，重新导入源码后没有问题

**Comment by pengwei1024** [comment]
请问下什么情况出现这个错误的呢？要么是注入 JS 出问题了，要么是执行回调注入 JS 出问题了，我提供的 release 已经混淆了,端上完全 keep 就行了
```
-keep class com.apkfuns.jsbridge.**{*;}
-keep class * extends com.apkfuns.jsbridge.module.JsModule
```

**Comment by hjw541988478** [comment]
我是在 debug 模式下运行的，感觉也挺奇怪的，跑 demo 是没问题的，在项目中 compile 使用就会出现问题，后面直接把 JsBridge 源码导入后也正常了，错误一直都是 `Error SyntaxError: Unexpected end of input` 这个错误，也是奇了怪了。

**Comment by pengwei1024** [comment]
多谢反馈，我检查下 gradle 依赖的代码是否有问题
